---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_07"

"ID": "20001234"
"FILES":
    - "/**your-path-to-root**/cau-dralg-2023/assignment_07/sort.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
