---

"COURSE": "CAU_DRALG_2023"
"ASSIGNMENT": "ASSIGNMENT_04"

"ID": "20001234"
"FILES":
    - "/**your-path-to-root**/cau-dralg-2023/assignment_04/history.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
    - "PROBLEM_05"
    - "PROBLEM_06"
        
